// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.30.0
// 	protoc        v4.22.3
// source: api/proto/externalApi.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RegParamsReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	HardId     int32   `protobuf:"varint,1,opt,name=HardId,proto3" json:"HardId,omitempty"`
	Token      string  `protobuf:"bytes,2,opt,name=Token,proto3" json:"Token,omitempty"`
	ParamName  string  `protobuf:"bytes,3,opt,name=ParamName,proto3" json:"ParamName,omitempty"`
	ParamValue float32 `protobuf:"fixed32,4,opt,name=ParamValue,proto3" json:"ParamValue,omitempty"`
}

func (x *RegParamsReq) Reset() {
	*x = RegParamsReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_proto_externalApi_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RegParamsReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegParamsReq) ProtoMessage() {}

func (x *RegParamsReq) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_externalApi_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegParamsReq.ProtoReflect.Descriptor instead.
func (*RegParamsReq) Descriptor() ([]byte, []int) {
	return file_api_proto_externalApi_proto_rawDescGZIP(), []int{0}
}

func (x *RegParamsReq) GetHardId() int32 {
	if x != nil {
		return x.HardId
	}
	return 0
}

func (x *RegParamsReq) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *RegParamsReq) GetParamName() string {
	if x != nil {
		return x.ParamName
	}
	return ""
}

func (x *RegParamsReq) GetParamValue() float32 {
	if x != nil {
		return x.ParamValue
	}
	return 0
}

type RegParamsResponce struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	MessageId string `protobuf:"bytes,1,opt,name=MessageId,proto3" json:"MessageId,omitempty"`
	ErrorCode string `protobuf:"bytes,2,opt,name=ErrorCode,proto3" json:"ErrorCode,omitempty"`
}

func (x *RegParamsResponce) Reset() {
	*x = RegParamsResponce{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_proto_externalApi_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RegParamsResponce) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegParamsResponce) ProtoMessage() {}

func (x *RegParamsResponce) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_externalApi_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegParamsResponce.ProtoReflect.Descriptor instead.
func (*RegParamsResponce) Descriptor() ([]byte, []int) {
	return file_api_proto_externalApi_proto_rawDescGZIP(), []int{1}
}

func (x *RegParamsResponce) GetMessageId() string {
	if x != nil {
		return x.MessageId
	}
	return ""
}

func (x *RegParamsResponce) GetErrorCode() string {
	if x != nil {
		return x.ErrorCode
	}
	return ""
}

type HardwareRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	HarwareId int32  `protobuf:"varint,1,opt,name=HarwareId,proto3" json:"HarwareId,omitempty"`
	Token     string `protobuf:"bytes,2,opt,name=Token,proto3" json:"Token,omitempty"`
}

func (x *HardwareRequest) Reset() {
	*x = HardwareRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_proto_externalApi_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *HardwareRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HardwareRequest) ProtoMessage() {}

func (x *HardwareRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_externalApi_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HardwareRequest.ProtoReflect.Descriptor instead.
func (*HardwareRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_externalApi_proto_rawDescGZIP(), []int{2}
}

func (x *HardwareRequest) GetHarwareId() int32 {
	if x != nil {
		return x.HarwareId
	}
	return 0
}

func (x *HardwareRequest) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

type HardwareParams struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ParamName  string  `protobuf:"bytes,1,opt,name=ParamName,proto3" json:"ParamName,omitempty"`
	ParamValue float32 `protobuf:"fixed32,2,opt,name=ParamValue,proto3" json:"ParamValue,omitempty"`
}

func (x *HardwareParams) Reset() {
	*x = HardwareParams{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_proto_externalApi_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *HardwareParams) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HardwareParams) ProtoMessage() {}

func (x *HardwareParams) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_externalApi_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HardwareParams.ProtoReflect.Descriptor instead.
func (*HardwareParams) Descriptor() ([]byte, []int) {
	return file_api_proto_externalApi_proto_rawDescGZIP(), []int{3}
}

func (x *HardwareParams) GetParamName() string {
	if x != nil {
		return x.ParamName
	}
	return ""
}

func (x *HardwareParams) GetParamValue() float32 {
	if x != nil {
		return x.ParamValue
	}
	return 0
}

type HardwareResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	MessageId string            `protobuf:"bytes,1,opt,name=MessageId,proto3" json:"MessageId,omitempty"`
	Params    []*HardwareParams `protobuf:"bytes,2,rep,name=Params,proto3" json:"Params,omitempty"`
}

func (x *HardwareResponse) Reset() {
	*x = HardwareResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_proto_externalApi_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *HardwareResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HardwareResponse) ProtoMessage() {}

func (x *HardwareResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_externalApi_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HardwareResponse.ProtoReflect.Descriptor instead.
func (*HardwareResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_externalApi_proto_rawDescGZIP(), []int{4}
}

func (x *HardwareResponse) GetMessageId() string {
	if x != nil {
		return x.MessageId
	}
	return ""
}

func (x *HardwareResponse) GetParams() []*HardwareParams {
	if x != nil {
		return x.Params
	}
	return nil
}

type UpdateParams struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ParamId    int32   `protobuf:"varint,1,opt,name=ParamId,proto3" json:"ParamId,omitempty"`
	ParamValue float32 `protobuf:"fixed32,2,opt,name=ParamValue,proto3" json:"ParamValue,omitempty"`
}

func (x *UpdateParams) Reset() {
	*x = UpdateParams{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_proto_externalApi_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateParams) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateParams) ProtoMessage() {}

func (x *UpdateParams) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_externalApi_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateParams.ProtoReflect.Descriptor instead.
func (*UpdateParams) Descriptor() ([]byte, []int) {
	return file_api_proto_externalApi_proto_rawDescGZIP(), []int{5}
}

func (x *UpdateParams) GetParamId() int32 {
	if x != nil {
		return x.ParamId
	}
	return 0
}

func (x *UpdateParams) GetParamValue() float32 {
	if x != nil {
		return x.ParamValue
	}
	return 0
}

type UpdateRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	HardwareId int32           `protobuf:"varint,1,opt,name=HardwareId,proto3" json:"HardwareId,omitempty"`
	Token      string          `protobuf:"bytes,2,opt,name=Token,proto3" json:"Token,omitempty"`
	Params     []*UpdateParams `protobuf:"bytes,3,rep,name=Params,proto3" json:"Params,omitempty"`
}

func (x *UpdateRequest) Reset() {
	*x = UpdateRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_proto_externalApi_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateRequest) ProtoMessage() {}

func (x *UpdateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_externalApi_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateRequest.ProtoReflect.Descriptor instead.
func (*UpdateRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_externalApi_proto_rawDescGZIP(), []int{6}
}

func (x *UpdateRequest) GetHardwareId() int32 {
	if x != nil {
		return x.HardwareId
	}
	return 0
}

func (x *UpdateRequest) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *UpdateRequest) GetParams() []*UpdateParams {
	if x != nil {
		return x.Params
	}
	return nil
}

type UpdateResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	MessageId string `protobuf:"bytes,1,opt,name=MessageId,proto3" json:"MessageId,omitempty"`
	ErrorCode string `protobuf:"bytes,2,opt,name=ErrorCode,proto3" json:"ErrorCode,omitempty"`
}

func (x *UpdateResponse) Reset() {
	*x = UpdateResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_proto_externalApi_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateResponse) ProtoMessage() {}

func (x *UpdateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_externalApi_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateResponse.ProtoReflect.Descriptor instead.
func (*UpdateResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_externalApi_proto_rawDescGZIP(), []int{7}
}

func (x *UpdateResponse) GetMessageId() string {
	if x != nil {
		return x.MessageId
	}
	return ""
}

func (x *UpdateResponse) GetErrorCode() string {
	if x != nil {
		return x.ErrorCode
	}
	return ""
}

type RegistrationRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Login    string `protobuf:"bytes,1,opt,name=Login,proto3" json:"Login,omitempty"`
	Password string `protobuf:"bytes,2,opt,name=Password,proto3" json:"Password,omitempty"`
}

func (x *RegistrationRequest) Reset() {
	*x = RegistrationRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_proto_externalApi_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RegistrationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegistrationRequest) ProtoMessage() {}

func (x *RegistrationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_externalApi_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegistrationRequest.ProtoReflect.Descriptor instead.
func (*RegistrationRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_externalApi_proto_rawDescGZIP(), []int{8}
}

func (x *RegistrationRequest) GetLogin() string {
	if x != nil {
		return x.Login
	}
	return ""
}

func (x *RegistrationRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

type RegistrationResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	MessageId string `protobuf:"bytes,1,opt,name=MessageId,proto3" json:"MessageId,omitempty"`
	ErrorCode string `protobuf:"bytes,2,opt,name=ErrorCode,proto3" json:"ErrorCode,omitempty"`
}

func (x *RegistrationResponse) Reset() {
	*x = RegistrationResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_proto_externalApi_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RegistrationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegistrationResponse) ProtoMessage() {}

func (x *RegistrationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_externalApi_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegistrationResponse.ProtoReflect.Descriptor instead.
func (*RegistrationResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_externalApi_proto_rawDescGZIP(), []int{9}
}

func (x *RegistrationResponse) GetMessageId() string {
	if x != nil {
		return x.MessageId
	}
	return ""
}

func (x *RegistrationResponse) GetErrorCode() string {
	if x != nil {
		return x.ErrorCode
	}
	return ""
}

type RegistrationHardwareResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	MessageId string `protobuf:"bytes,1,opt,name=MessageId,proto3" json:"MessageId,omitempty"`
	ErrorCode string `protobuf:"bytes,2,opt,name=ErrorCode,proto3" json:"ErrorCode,omitempty"`
	HardId    int32  `protobuf:"varint,3,opt,name=HardId,proto3" json:"HardId,omitempty"`
}

func (x *RegistrationHardwareResponse) Reset() {
	*x = RegistrationHardwareResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_proto_externalApi_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RegistrationHardwareResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegistrationHardwareResponse) ProtoMessage() {}

func (x *RegistrationHardwareResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_externalApi_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegistrationHardwareResponse.ProtoReflect.Descriptor instead.
func (*RegistrationHardwareResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_externalApi_proto_rawDescGZIP(), []int{10}
}

func (x *RegistrationHardwareResponse) GetMessageId() string {
	if x != nil {
		return x.MessageId
	}
	return ""
}

func (x *RegistrationHardwareResponse) GetErrorCode() string {
	if x != nil {
		return x.ErrorCode
	}
	return ""
}

func (x *RegistrationHardwareResponse) GetHardId() int32 {
	if x != nil {
		return x.HardId
	}
	return 0
}

type RegistrationHardwareRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	HardName string `protobuf:"bytes,1,opt,name=HardName,proto3" json:"HardName,omitempty"`
	Ip       string `protobuf:"bytes,2,opt,name=Ip,proto3" json:"Ip,omitempty"`
	Token    string `protobuf:"bytes,3,opt,name=Token,proto3" json:"Token,omitempty"`
}

func (x *RegistrationHardwareRequest) Reset() {
	*x = RegistrationHardwareRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_proto_externalApi_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RegistrationHardwareRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegistrationHardwareRequest) ProtoMessage() {}

func (x *RegistrationHardwareRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_externalApi_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegistrationHardwareRequest.ProtoReflect.Descriptor instead.
func (*RegistrationHardwareRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_externalApi_proto_rawDescGZIP(), []int{11}
}

func (x *RegistrationHardwareRequest) GetHardName() string {
	if x != nil {
		return x.HardName
	}
	return ""
}

func (x *RegistrationHardwareRequest) GetIp() string {
	if x != nil {
		return x.Ip
	}
	return ""
}

func (x *RegistrationHardwareRequest) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

type HardwareIdRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Token string `protobuf:"bytes,1,opt,name=Token,proto3" json:"Token,omitempty"`
}

func (x *HardwareIdRequest) Reset() {
	*x = HardwareIdRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_proto_externalApi_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *HardwareIdRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HardwareIdRequest) ProtoMessage() {}

func (x *HardwareIdRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_externalApi_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HardwareIdRequest.ProtoReflect.Descriptor instead.
func (*HardwareIdRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_externalApi_proto_rawDescGZIP(), []int{12}
}

func (x *HardwareIdRequest) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

type HardwereIdResponce struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	MessageId string           `protobuf:"bytes,1,opt,name=MessageId,proto3" json:"MessageId,omitempty"`
	Rows      []*HardwareIdAll `protobuf:"bytes,2,rep,name=Rows,proto3" json:"Rows,omitempty"`
}

func (x *HardwereIdResponce) Reset() {
	*x = HardwereIdResponce{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_proto_externalApi_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *HardwereIdResponce) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HardwereIdResponce) ProtoMessage() {}

func (x *HardwereIdResponce) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_externalApi_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HardwereIdResponce.ProtoReflect.Descriptor instead.
func (*HardwereIdResponce) Descriptor() ([]byte, []int) {
	return file_api_proto_externalApi_proto_rawDescGZIP(), []int{13}
}

func (x *HardwereIdResponce) GetMessageId() string {
	if x != nil {
		return x.MessageId
	}
	return ""
}

func (x *HardwereIdResponce) GetRows() []*HardwareIdAll {
	if x != nil {
		return x.Rows
	}
	return nil
}

type HardwareIdAll struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	HardwareName string `protobuf:"bytes,1,opt,name=HardwareName,proto3" json:"HardwareName,omitempty"`
	HardwareId   int32  `protobuf:"varint,2,opt,name=HardwareId,proto3" json:"HardwareId,omitempty"`
}

func (x *HardwareIdAll) Reset() {
	*x = HardwareIdAll{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_proto_externalApi_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *HardwareIdAll) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HardwareIdAll) ProtoMessage() {}

func (x *HardwareIdAll) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_externalApi_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HardwareIdAll.ProtoReflect.Descriptor instead.
func (*HardwareIdAll) Descriptor() ([]byte, []int) {
	return file_api_proto_externalApi_proto_rawDescGZIP(), []int{14}
}

func (x *HardwareIdAll) GetHardwareName() string {
	if x != nil {
		return x.HardwareName
	}
	return ""
}

func (x *HardwareIdAll) GetHardwareId() int32 {
	if x != nil {
		return x.HardwareId
	}
	return 0
}

type ParamIdRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Token      string `protobuf:"bytes,1,opt,name=Token,proto3" json:"Token,omitempty"`
	HardwareId int32  `protobuf:"varint,2,opt,name=HardwareId,proto3" json:"HardwareId,omitempty"`
}

func (x *ParamIdRequest) Reset() {
	*x = ParamIdRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_proto_externalApi_proto_msgTypes[15]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ParamIdRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ParamIdRequest) ProtoMessage() {}

func (x *ParamIdRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_externalApi_proto_msgTypes[15]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ParamIdRequest.ProtoReflect.Descriptor instead.
func (*ParamIdRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_externalApi_proto_rawDescGZIP(), []int{15}
}

func (x *ParamIdRequest) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *ParamIdRequest) GetHardwareId() int32 {
	if x != nil {
		return x.HardwareId
	}
	return 0
}

type ParamIdResponce struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	MessageId string        `protobuf:"bytes,1,opt,name=MessageId,proto3" json:"MessageId,omitempty"`
	Rows      []*ParamIdAll `protobuf:"bytes,2,rep,name=Rows,proto3" json:"Rows,omitempty"`
}

func (x *ParamIdResponce) Reset() {
	*x = ParamIdResponce{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_proto_externalApi_proto_msgTypes[16]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ParamIdResponce) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ParamIdResponce) ProtoMessage() {}

func (x *ParamIdResponce) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_externalApi_proto_msgTypes[16]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ParamIdResponce.ProtoReflect.Descriptor instead.
func (*ParamIdResponce) Descriptor() ([]byte, []int) {
	return file_api_proto_externalApi_proto_rawDescGZIP(), []int{16}
}

func (x *ParamIdResponce) GetMessageId() string {
	if x != nil {
		return x.MessageId
	}
	return ""
}

func (x *ParamIdResponce) GetRows() []*ParamIdAll {
	if x != nil {
		return x.Rows
	}
	return nil
}

type ParamIdAll struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ParamName string `protobuf:"bytes,1,opt,name=ParamName,proto3" json:"ParamName,omitempty"`
	ParamId   int32  `protobuf:"varint,2,opt,name=ParamId,proto3" json:"ParamId,omitempty"`
}

func (x *ParamIdAll) Reset() {
	*x = ParamIdAll{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_proto_externalApi_proto_msgTypes[17]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ParamIdAll) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ParamIdAll) ProtoMessage() {}

func (x *ParamIdAll) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_externalApi_proto_msgTypes[17]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ParamIdAll.ProtoReflect.Descriptor instead.
func (*ParamIdAll) Descriptor() ([]byte, []int) {
	return file_api_proto_externalApi_proto_rawDescGZIP(), []int{17}
}

func (x *ParamIdAll) GetParamName() string {
	if x != nil {
		return x.ParamName
	}
	return ""
}

func (x *ParamIdAll) GetParamId() int32 {
	if x != nil {
		return x.ParamId
	}
	return 0
}

var File_api_proto_externalApi_proto protoreflect.FileDescriptor

var file_api_proto_externalApi_proto_rawDesc = []byte{
	0x0a, 0x1b, 0x61, 0x70, 0x69, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x65, 0x78, 0x74, 0x65,
	0x72, 0x6e, 0x61, 0x6c, 0x41, 0x70, 0x69, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x03, 0x61,
	0x70, 0x69, 0x22, 0x7a, 0x0a, 0x0c, 0x52, 0x65, 0x67, 0x50, 0x61, 0x72, 0x61, 0x6d, 0x73, 0x52,
	0x65, 0x71, 0x12, 0x16, 0x0a, 0x06, 0x48, 0x61, 0x72, 0x64, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x05, 0x52, 0x06, 0x48, 0x61, 0x72, 0x64, 0x49, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x54, 0x6f,
	0x6b, 0x65, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x54, 0x6f, 0x6b, 0x65, 0x6e,
	0x12, 0x1c, 0x0a, 0x09, 0x50, 0x61, 0x72, 0x61, 0x6d, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x09, 0x50, 0x61, 0x72, 0x61, 0x6d, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x1e,
	0x0a, 0x0a, 0x50, 0x61, 0x72, 0x61, 0x6d, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x04, 0x20, 0x01,
	0x28, 0x02, 0x52, 0x0a, 0x50, 0x61, 0x72, 0x61, 0x6d, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x22, 0x4f,
	0x0a, 0x11, 0x52, 0x65, 0x67, 0x50, 0x61, 0x72, 0x61, 0x6d, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x63, 0x65, 0x12, 0x1c, 0x0a, 0x09, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x49, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x49,
	0x64, 0x12, 0x1c, 0x0a, 0x09, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x43, 0x6f, 0x64, 0x65, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x43, 0x6f, 0x64, 0x65, 0x22,
	0x45, 0x0a, 0x0f, 0x48, 0x61, 0x72, 0x64, 0x77, 0x61, 0x72, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x12, 0x1c, 0x0a, 0x09, 0x48, 0x61, 0x72, 0x77, 0x61, 0x72, 0x65, 0x49, 0x64, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x09, 0x48, 0x61, 0x72, 0x77, 0x61, 0x72, 0x65, 0x49, 0x64,
	0x12, 0x14, 0x0a, 0x05, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x05, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x22, 0x4e, 0x0a, 0x0e, 0x48, 0x61, 0x72, 0x64, 0x77, 0x61,
	0x72, 0x65, 0x50, 0x61, 0x72, 0x61, 0x6d, 0x73, 0x12, 0x1c, 0x0a, 0x09, 0x50, 0x61, 0x72, 0x61,
	0x6d, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x50, 0x61, 0x72,
	0x61, 0x6d, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x1e, 0x0a, 0x0a, 0x50, 0x61, 0x72, 0x61, 0x6d, 0x56,
	0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x02, 0x52, 0x0a, 0x50, 0x61, 0x72, 0x61,
	0x6d, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x22, 0x5d, 0x0a, 0x10, 0x48, 0x61, 0x72, 0x64, 0x77, 0x61,
	0x72, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x1c, 0x0a, 0x09, 0x4d, 0x65,
	0x73, 0x73, 0x61, 0x67, 0x65, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x4d,
	0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x49, 0x64, 0x12, 0x2b, 0x0a, 0x06, 0x50, 0x61, 0x72, 0x61,
	0x6d, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x13, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x48,
	0x61, 0x72, 0x64, 0x77, 0x61, 0x72, 0x65, 0x50, 0x61, 0x72, 0x61, 0x6d, 0x73, 0x52, 0x06, 0x50,
	0x61, 0x72, 0x61, 0x6d, 0x73, 0x22, 0x48, 0x0a, 0x0c, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x50,
	0x61, 0x72, 0x61, 0x6d, 0x73, 0x12, 0x18, 0x0a, 0x07, 0x50, 0x61, 0x72, 0x61, 0x6d, 0x49, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x07, 0x50, 0x61, 0x72, 0x61, 0x6d, 0x49, 0x64, 0x12,
	0x1e, 0x0a, 0x0a, 0x50, 0x61, 0x72, 0x61, 0x6d, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x02, 0x52, 0x0a, 0x50, 0x61, 0x72, 0x61, 0x6d, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x22,
	0x70, 0x0a, 0x0d, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x12, 0x1e, 0x0a, 0x0a, 0x48, 0x61, 0x72, 0x64, 0x77, 0x61, 0x72, 0x65, 0x49, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x05, 0x52, 0x0a, 0x48, 0x61, 0x72, 0x64, 0x77, 0x61, 0x72, 0x65, 0x49, 0x64,
	0x12, 0x14, 0x0a, 0x05, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x05, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x12, 0x29, 0x0a, 0x06, 0x50, 0x61, 0x72, 0x61, 0x6d, 0x73,
	0x18, 0x03, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x11, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x55, 0x70, 0x64,
	0x61, 0x74, 0x65, 0x50, 0x61, 0x72, 0x61, 0x6d, 0x73, 0x52, 0x06, 0x50, 0x61, 0x72, 0x61, 0x6d,
	0x73, 0x22, 0x4c, 0x0a, 0x0e, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x12, 0x1c, 0x0a, 0x09, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x49, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x49,
	0x64, 0x12, 0x1c, 0x0a, 0x09, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x43, 0x6f, 0x64, 0x65, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x43, 0x6f, 0x64, 0x65, 0x22,
	0x47, 0x0a, 0x13, 0x52, 0x65, 0x67, 0x69, 0x73, 0x74, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x4c, 0x6f, 0x67, 0x69, 0x6e, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x4c, 0x6f, 0x67, 0x69, 0x6e, 0x12, 0x1a, 0x0a, 0x08,
	0x50, 0x61, 0x73, 0x73, 0x77, 0x6f, 0x72, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08,
	0x50, 0x61, 0x73, 0x73, 0x77, 0x6f, 0x72, 0x64, 0x22, 0x52, 0x0a, 0x14, 0x52, 0x65, 0x67, 0x69,
	0x73, 0x74, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x12, 0x1c, 0x0a, 0x09, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x49, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x09, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x49, 0x64, 0x12, 0x1c,
	0x0a, 0x09, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x43, 0x6f, 0x64, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x09, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x43, 0x6f, 0x64, 0x65, 0x22, 0x72, 0x0a, 0x1c,
	0x52, 0x65, 0x67, 0x69, 0x73, 0x74, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x48, 0x61, 0x72, 0x64,
	0x77, 0x61, 0x72, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x1c, 0x0a, 0x09,
	0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x09, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x49, 0x64, 0x12, 0x1c, 0x0a, 0x09, 0x45, 0x72,
	0x72, 0x6f, 0x72, 0x43, 0x6f, 0x64, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x45,
	0x72, 0x72, 0x6f, 0x72, 0x43, 0x6f, 0x64, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x48, 0x61, 0x72, 0x64,
	0x49, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x48, 0x61, 0x72, 0x64, 0x49, 0x64,
	0x22, 0x5f, 0x0a, 0x1b, 0x52, 0x65, 0x67, 0x69, 0x73, 0x74, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e,
	0x48, 0x61, 0x72, 0x64, 0x77, 0x61, 0x72, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12,
	0x1a, 0x0a, 0x08, 0x48, 0x61, 0x72, 0x64, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x08, 0x48, 0x61, 0x72, 0x64, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x0e, 0x0a, 0x02, 0x49,
	0x70, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x49, 0x70, 0x12, 0x14, 0x0a, 0x05, 0x54,
	0x6f, 0x6b, 0x65, 0x6e, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x54, 0x6f, 0x6b, 0x65,
	0x6e, 0x22, 0x29, 0x0a, 0x11, 0x48, 0x61, 0x72, 0x64, 0x77, 0x61, 0x72, 0x65, 0x49, 0x64, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x22, 0x5a, 0x0a, 0x12,
	0x48, 0x61, 0x72, 0x64, 0x77, 0x65, 0x72, 0x65, 0x49, 0x64, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x63, 0x65, 0x12, 0x1c, 0x0a, 0x09, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x49, 0x64, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x49, 0x64,
	0x12, 0x26, 0x0a, 0x04, 0x52, 0x6f, 0x77, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x12,
	0x2e, 0x61, 0x70, 0x69, 0x2e, 0x48, 0x61, 0x72, 0x64, 0x77, 0x61, 0x72, 0x65, 0x49, 0x64, 0x41,
	0x6c, 0x6c, 0x52, 0x04, 0x52, 0x6f, 0x77, 0x73, 0x22, 0x53, 0x0a, 0x0d, 0x48, 0x61, 0x72, 0x64,
	0x77, 0x61, 0x72, 0x65, 0x49, 0x64, 0x41, 0x6c, 0x6c, 0x12, 0x22, 0x0a, 0x0c, 0x48, 0x61, 0x72,
	0x64, 0x77, 0x61, 0x72, 0x65, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x0c, 0x48, 0x61, 0x72, 0x64, 0x77, 0x61, 0x72, 0x65, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x1e, 0x0a,
	0x0a, 0x48, 0x61, 0x72, 0x64, 0x77, 0x61, 0x72, 0x65, 0x49, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x05, 0x52, 0x0a, 0x48, 0x61, 0x72, 0x64, 0x77, 0x61, 0x72, 0x65, 0x49, 0x64, 0x22, 0x46, 0x0a,
	0x0e, 0x50, 0x61, 0x72, 0x61, 0x6d, 0x49, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12,
	0x14, 0x0a, 0x05, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05,
	0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x12, 0x1e, 0x0a, 0x0a, 0x48, 0x61, 0x72, 0x64, 0x77, 0x61, 0x72,
	0x65, 0x49, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0a, 0x48, 0x61, 0x72, 0x64, 0x77,
	0x61, 0x72, 0x65, 0x49, 0x64, 0x22, 0x54, 0x0a, 0x0f, 0x50, 0x61, 0x72, 0x61, 0x6d, 0x49, 0x64,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x63, 0x65, 0x12, 0x1c, 0x0a, 0x09, 0x4d, 0x65, 0x73, 0x73,
	0x61, 0x67, 0x65, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x4d, 0x65, 0x73,
	0x73, 0x61, 0x67, 0x65, 0x49, 0x64, 0x12, 0x23, 0x0a, 0x04, 0x52, 0x6f, 0x77, 0x73, 0x18, 0x02,
	0x20, 0x03, 0x28, 0x0b, 0x32, 0x0f, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x50, 0x61, 0x72, 0x61, 0x6d,
	0x49, 0x64, 0x41, 0x6c, 0x6c, 0x52, 0x04, 0x52, 0x6f, 0x77, 0x73, 0x22, 0x44, 0x0a, 0x0a, 0x50,
	0x61, 0x72, 0x61, 0x6d, 0x49, 0x64, 0x41, 0x6c, 0x6c, 0x12, 0x1c, 0x0a, 0x09, 0x50, 0x61, 0x72,
	0x61, 0x6d, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x50, 0x61,
	0x72, 0x61, 0x6d, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x50, 0x61, 0x72, 0x61, 0x6d,
	0x49, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x07, 0x50, 0x61, 0x72, 0x61, 0x6d, 0x49,
	0x64, 0x32, 0xef, 0x03, 0x0a, 0x03, 0x61, 0x70, 0x69, 0x12, 0x41, 0x0a, 0x10, 0x47, 0x65, 0x74,
	0x48, 0x61, 0x72, 0x64, 0x77, 0x61, 0x72, 0x65, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x12, 0x14, 0x2e,
	0x61, 0x70, 0x69, 0x2e, 0x48, 0x61, 0x72, 0x64, 0x77, 0x61, 0x72, 0x65, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x1a, 0x15, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x48, 0x61, 0x72, 0x64, 0x77, 0x61,
	0x72, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x3d, 0x0a, 0x10,
	0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x50, 0x61, 0x72, 0x61, 0x6d, 0x56, 0x61, 0x6c, 0x75, 0x65,
	0x12, 0x12, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x1a, 0x13, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x55, 0x70, 0x64, 0x61, 0x74,
	0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x45, 0x0a, 0x0c, 0x52,
	0x65, 0x67, 0x69, 0x73, 0x74, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x18, 0x2e, 0x61, 0x70,
	0x69, 0x2e, 0x52, 0x65, 0x67, 0x69, 0x73, 0x74, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x19, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x52, 0x65, 0x67, 0x69,
	0x73, 0x74, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x22, 0x00, 0x12, 0x5d, 0x0a, 0x14, 0x52, 0x65, 0x67, 0x69, 0x73, 0x74, 0x72, 0x61, 0x74, 0x69,
	0x6f, 0x6e, 0x48, 0x61, 0x72, 0x64, 0x77, 0x61, 0x72, 0x65, 0x12, 0x20, 0x2e, 0x61, 0x70, 0x69,
	0x2e, 0x52, 0x65, 0x67, 0x69, 0x73, 0x74, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x48, 0x61, 0x72,
	0x64, 0x77, 0x61, 0x72, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x21, 0x2e, 0x61,
	0x70, 0x69, 0x2e, 0x52, 0x65, 0x67, 0x69, 0x73, 0x74, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x48,
	0x61, 0x72, 0x64, 0x77, 0x61, 0x72, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22,
	0x00, 0x12, 0x42, 0x0a, 0x0d, 0x47, 0x65, 0x74, 0x48, 0x61, 0x72, 0x64, 0x77, 0x61, 0x72, 0x65,
	0x49, 0x64, 0x12, 0x16, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x48, 0x61, 0x72, 0x64, 0x77, 0x61, 0x72,
	0x65, 0x49, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x17, 0x2e, 0x61, 0x70, 0x69,
	0x2e, 0x48, 0x61, 0x72, 0x64, 0x77, 0x65, 0x72, 0x65, 0x49, 0x64, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x63, 0x65, 0x22, 0x00, 0x12, 0x39, 0x0a, 0x0a, 0x47, 0x65, 0x74, 0x50, 0x61, 0x72, 0x61,
	0x6d, 0x49, 0x64, 0x12, 0x13, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x50, 0x61, 0x72, 0x61, 0x6d, 0x49,
	0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x14, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x50,
	0x61, 0x72, 0x61, 0x6d, 0x49, 0x64, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x63, 0x65, 0x22, 0x00,
	0x12, 0x41, 0x0a, 0x12, 0x52, 0x65, 0x67, 0x69, 0x73, 0x74, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e,
	0x50, 0x61, 0x72, 0x61, 0x6d, 0x73, 0x12, 0x11, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x52, 0x65, 0x67,
	0x50, 0x61, 0x72, 0x61, 0x6d, 0x73, 0x52, 0x65, 0x71, 0x1a, 0x16, 0x2e, 0x61, 0x70, 0x69, 0x2e,
	0x52, 0x65, 0x67, 0x50, 0x61, 0x72, 0x61, 0x6d, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x63,
	0x65, 0x22, 0x00, 0x42, 0x0b, 0x5a, 0x09, 0x61, 0x70, 0x69, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_api_proto_externalApi_proto_rawDescOnce sync.Once
	file_api_proto_externalApi_proto_rawDescData = file_api_proto_externalApi_proto_rawDesc
)

func file_api_proto_externalApi_proto_rawDescGZIP() []byte {
	file_api_proto_externalApi_proto_rawDescOnce.Do(func() {
		file_api_proto_externalApi_proto_rawDescData = protoimpl.X.CompressGZIP(file_api_proto_externalApi_proto_rawDescData)
	})
	return file_api_proto_externalApi_proto_rawDescData
}

var file_api_proto_externalApi_proto_msgTypes = make([]protoimpl.MessageInfo, 18)
var file_api_proto_externalApi_proto_goTypes = []interface{}{
	(*RegParamsReq)(nil),                 // 0: api.RegParamsReq
	(*RegParamsResponce)(nil),            // 1: api.RegParamsResponce
	(*HardwareRequest)(nil),              // 2: api.HardwareRequest
	(*HardwareParams)(nil),               // 3: api.HardwareParams
	(*HardwareResponse)(nil),             // 4: api.HardwareResponse
	(*UpdateParams)(nil),                 // 5: api.UpdateParams
	(*UpdateRequest)(nil),                // 6: api.UpdateRequest
	(*UpdateResponse)(nil),               // 7: api.UpdateResponse
	(*RegistrationRequest)(nil),          // 8: api.RegistrationRequest
	(*RegistrationResponse)(nil),         // 9: api.RegistrationResponse
	(*RegistrationHardwareResponse)(nil), // 10: api.RegistrationHardwareResponse
	(*RegistrationHardwareRequest)(nil),  // 11: api.RegistrationHardwareRequest
	(*HardwareIdRequest)(nil),            // 12: api.HardwareIdRequest
	(*HardwereIdResponce)(nil),           // 13: api.HardwereIdResponce
	(*HardwareIdAll)(nil),                // 14: api.HardwareIdAll
	(*ParamIdRequest)(nil),               // 15: api.ParamIdRequest
	(*ParamIdResponce)(nil),              // 16: api.ParamIdResponce
	(*ParamIdAll)(nil),                   // 17: api.ParamIdAll
}
var file_api_proto_externalApi_proto_depIdxs = []int32{
	3,  // 0: api.HardwareResponse.Params:type_name -> api.HardwareParams
	5,  // 1: api.UpdateRequest.Params:type_name -> api.UpdateParams
	14, // 2: api.HardwereIdResponce.Rows:type_name -> api.HardwareIdAll
	17, // 3: api.ParamIdResponce.Rows:type_name -> api.ParamIdAll
	2,  // 4: api.api.GetHardwareValue:input_type -> api.HardwareRequest
	6,  // 5: api.api.UpdateParamValue:input_type -> api.UpdateRequest
	8,  // 6: api.api.Registration:input_type -> api.RegistrationRequest
	11, // 7: api.api.RegistrationHardware:input_type -> api.RegistrationHardwareRequest
	12, // 8: api.api.GetHardwareId:input_type -> api.HardwareIdRequest
	15, // 9: api.api.GetParamId:input_type -> api.ParamIdRequest
	0,  // 10: api.api.RegistrationParams:input_type -> api.RegParamsReq
	4,  // 11: api.api.GetHardwareValue:output_type -> api.HardwareResponse
	7,  // 12: api.api.UpdateParamValue:output_type -> api.UpdateResponse
	9,  // 13: api.api.Registration:output_type -> api.RegistrationResponse
	10, // 14: api.api.RegistrationHardware:output_type -> api.RegistrationHardwareResponse
	13, // 15: api.api.GetHardwareId:output_type -> api.HardwereIdResponce
	16, // 16: api.api.GetParamId:output_type -> api.ParamIdResponce
	1,  // 17: api.api.RegistrationParams:output_type -> api.RegParamsResponce
	11, // [11:18] is the sub-list for method output_type
	4,  // [4:11] is the sub-list for method input_type
	4,  // [4:4] is the sub-list for extension type_name
	4,  // [4:4] is the sub-list for extension extendee
	0,  // [0:4] is the sub-list for field type_name
}

func init() { file_api_proto_externalApi_proto_init() }
func file_api_proto_externalApi_proto_init() {
	if File_api_proto_externalApi_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_api_proto_externalApi_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RegParamsReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_proto_externalApi_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RegParamsResponce); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_proto_externalApi_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*HardwareRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_proto_externalApi_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*HardwareParams); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_proto_externalApi_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*HardwareResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_proto_externalApi_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateParams); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_proto_externalApi_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_proto_externalApi_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_proto_externalApi_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RegistrationRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_proto_externalApi_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RegistrationResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_proto_externalApi_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RegistrationHardwareResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_proto_externalApi_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RegistrationHardwareRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_proto_externalApi_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*HardwareIdRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_proto_externalApi_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*HardwereIdResponce); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_proto_externalApi_proto_msgTypes[14].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*HardwareIdAll); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_proto_externalApi_proto_msgTypes[15].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ParamIdRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_proto_externalApi_proto_msgTypes[16].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ParamIdResponce); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_proto_externalApi_proto_msgTypes[17].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ParamIdAll); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_api_proto_externalApi_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   18,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_proto_externalApi_proto_goTypes,
		DependencyIndexes: file_api_proto_externalApi_proto_depIdxs,
		MessageInfos:      file_api_proto_externalApi_proto_msgTypes,
	}.Build()
	File_api_proto_externalApi_proto = out.File
	file_api_proto_externalApi_proto_rawDesc = nil
	file_api_proto_externalApi_proto_goTypes = nil
	file_api_proto_externalApi_proto_depIdxs = nil
}
